import { Provider } from '@angular/core';
import {
  STUDIO_API,
  HttpStudioApi,
  MockStudioApi,
  ALBUMS_API,
  ANALYSIS_API,
  AUTH_API,
  CLIENT_GALLERIES_API,
  CONTENT_API,
  DISCOUNTS_API,
  EQUIPMENT_API,
  PHOTOGRAPHERS_API,
  PHOTOS_API,
  PRINT_OPTIONS_API,
  PRINT_REQUESTS_API,
  PROMOTIONS_API,
  PUBLIC_GALLERIES_API,
  QUOTES_API,
  RATES_API,
  SESSIONS_API,
  STUDIOS_API,
  UPLOADS_API,
  VENDORS_API,
} from '@qbs/api';
export function studioProviders(mock = false): Provider[] {
  return [
    { provide: STUDIO_API, useClass: mock ? MockStudioApi : HttpStudioApi },
    ...[
      ALBUMS_API,
      ANALYSIS_API,
      AUTH_API,
      CLIENT_GALLERIES_API,
      CONTENT_API,
      DISCOUNTS_API,
      EQUIPMENT_API,
      PHOTOGRAPHERS_API,
      PHOTOS_API,
      PRINT_OPTIONS_API,
      PRINT_REQUESTS_API,
      PROMOTIONS_API,
      PUBLIC_GALLERIES_API,
      QUOTES_API,
      RATES_API,
      SESSIONS_API,
      STUDIOS_API,
      UPLOADS_API,
      VENDORS_API,
    ].map((token) => ({ provide: token, useExisting: STUDIO_API })),
  ];
}
