@startuml
!include <C4/C4_Context>
LAYOUT_WITH_LEGEND()
title System context - Check session availability
Person(actor0, "Public visitor", "Uses the Marketing application")
System(studio, "Quinntyne Brown Studio", "Photography studio platform")
Rel(actor0, studio, "Check session availability")
@enduml
