import { readFileSync, writeFileSync } from 'node:fs';
const manifest = JSON.parse(readFileSync(new URL('../frontend/component-catalog.json', import.meta.url), 'utf8'));
writeFileSync(new URL('../frontend/projects/application/src/lib/component-contracts.ts', import.meta.url),
  '// Generated by scripts/sync-catalog.mjs from frontend/component-catalog.json.\nexport const COMPONENT_CONTRACTS = ' + JSON.stringify(manifest, null, 2) + ';\n');
